<a href="https://colab.research.google.com/github/rheahalebeed/BA305-A3-Billboard-Spotify-Project/blob/main/BA305ProjectCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

billboard = pd.read_csv("/content/drive/My Drive/BA 305 Project/billboard.csv")
audio_ft = pd.read_csv("/content/drive/My Drive/BA 305 Project/audio_features.csv")
billboard.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,url,week_id,week_position,song,performer,song_id,instance,previous_week_position,peak_position,weeks_on_chart
0,http://www.billboard.com/charts/hot-100/1965-0...,7/17/1965,34,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,45.0,34,4
1,http://www.billboard.com/charts/hot-100/1965-0...,7/24/1965,22,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,34.0,22,5
2,http://www.billboard.com/charts/hot-100/1965-0...,7/31/1965,14,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,22.0,14,6
3,http://www.billboard.com/charts/hot-100/1965-0...,8/7/1965,10,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,14.0,10,7
4,http://www.billboard.com/charts/hot-100/1965-0...,8/14/1965,8,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,10.0,8,8

In [17]:
print("Billboard shape:", billboard.shape)

print("Audio features shape:", audio_ft.shape)

print("Unique Billboard songs:", billboard["song_id"].nunique())

print("Unique Audio songs:", audio_ft["song_id"].nunique())

Billboard shape: (327895, 10)
Audio features shape: (29503, 22)
Unique Billboard songs: 29389
Unique Audio songs: 29386

In [18]:
print("Duplicate song_ids in audio features:",

      audio_ft["song_id"].duplicated().sum())

Duplicate song_ids in audio features: 117

In [19]:
audio_ft[audio_ft["song_id"].duplicated(keep=False)].sort_values("song_id").head(20)

,song_id,performer,song,spotify_genre,spotify_track_id,spotify_track_preview_url,spotify_track_duration_ms,spotify_track_explicit,spotify_track_album,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,spotify_track_popularity
344,24/7Meek Mill Featuring Ella Mai,Meek Mill Featuring Ella Mai,24/7,"['hip hop', 'philly rap', 'pop rap', 'rap', 's...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,24/7Meek Mill Featuring Ella Mai,Meek Mill Featuring Ella Mai,24/7,"['hip hop', 'philly rap', 'pop rap', 'rap', 's...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,A Holly Jolly ChristmasBurl Ives,Burl Ives,A Holly Jolly Christmas,"['adult standards', 'american folk revival']",65Q2mv3UlVi9eO70OpsmSe,NaN,135533.0,False,Have A Holly Jolly Christmas,0.683,...,-13.056,1.0,0.0303,0.57900,0.000000,0.0760,0.888,140.467,4.0,80.0
541,A Holly Jolly ChristmasBurl Ives,Burl Ives,A Holly Jolly Christmas,"['adult standards', 'american folk revival']",65Q2mv3UlVi9eO70OpsmSe,NaN,135533.0,False,Have A Holly Jolly Christmas,0.674,...,-12.937,1.0,0.0309,0.61600,0.000000,0.0781,0.862,140.352,4.0,82.0
803,Act UpCity Girls,City Girls,Act Up,"['pop', 'pop rap', 'trap queen']",3A2yGHWIzmGEIolwonU69h,NaN,158332.0,True,Girl Code,0.938,...,-4.713,1.0,0.1890,0.01670,0.000000,0.1110,0.313,97.075,4.0,79.0
804,Act UpCity Girls,City Girls,Act Up,"['pop', 'pop rap', 'trap queen']",3A2yGHWIzmGEIolwonU69h,NaN,158332.0,True,Girl Code,0.938,...,-4.713,1.0,0.1890,0.01670,0.000000,0.1110,0.313,97.075,4.0,80.0
1108,All I Want For Christmas Is YouMariah Carey,Mariah Carey,All I Want For Christmas Is You,"['dance pop', 'pop', 'r&b', 'urban contemporary']",0bYg9bo50gSsH3LtXe2SQn,https://p.scdn.co/mp3-preview/ab4f06069148ef85...,241106.0,False,Merry Christmas,0.335,...,-7.462,1.0,0.0386,0.16400,0.000000,0.0708,0.346,150.277,4.0,95.0
1109,All I Want For Christmas Is YouMariah Carey,Mariah Carey,All I Want For Christmas Is You,"['dance pop', 'pop', 'r&b', 'urban contemporary']",0bYg9bo50gSsH3LtXe2SQn,https://p.scdn.co/mp3-preview/ab4f06069148ef85...,241106.0,False,Merry Christmas,0.335,...,-7.462,1.0,0.0386,0.16400,0.000000,0.0708,0.346,150.277,4.0,97.0
1196,All The Good Girls Go To HellBillie Eilish,Billie Eilish,All The Good Girls Go To Hell,"['electropop', 'pop']",6IRdLKIyS4p7XNiP8r6rsx,NaN,168839.0,False,WHEN WE ALL FALL ASLEE,0.726,...,-8.922,0.0,0.3720,0.28300,0.143000,0.1770,0.569,185.044,4.0,86.0
1197,All The Good Girls Go To HellBillie Eilish,Billie Eilish,All The Good Girls Go To Hell,"['electropop', 'pop']",6IRdLKIyS4p7XNiP8r6rsx,NaN,168839.0,False,WHEN WE ALL FALL ASLEE,0.726,...,-8.922,0.0,0.3720,0.28300,0.143000,0.1770,0.569,185.044,4.0,87.0
1233,All To MyselfDan + Shay,Dan + Shay,All To Myself,"['contemporary country', 'pop']",08tq1XcHwVt5PHXUo87i0D,https://p.scdn.co/mp3-preview/65db44647a32d7b3...,169920.0,False,Dan + Shay,0.646,...,-4.616,1.0,0.0313,0.20800,0.000000,0.1250,0.565,94.975,4.0,73.0
1234,All To MyselfDan + Shay,Dan + Shay,All To Myself,"['contemporary country', 'pop']",08tq1XcHwVt5PHXUo87i0D,https://p.scdn.co/mp3-preview/65db44647a32d7b3...,169920.0,False,Dan + Shay,0.646,...,-4.616,1.0,0.0313,0.20800,0.000000,0.1250,0.565,94.975,4.0,74.0
2040,"Bacc At It AgainYella Beezy, Gucci Mane & Quavo","Yella Beezy, Gucci Mane & Quavo",Bacc At It Again,"['dfw rap', 'rap', 'southern hip hop', 'trap']",2biNa12dMbHJrHVFRt8JyO,https://p.scdn.co/mp3-preview/fa6fa6f6f363be29...,228185.0,True,Bacc At It Again,0.948,...,-5.725,0.0,0.1680,0.00124,0.000001,0.0716,0.856,135.979,4.0,62.0
2039,"Bacc At It AgainYella Beezy, Gucci Mane & Quavo","Yella Beezy, Gucci Mane & Quavo",Bacc At It Again,"['dfw rap', 'rap', 'southern hip hop', 'trap']",2biNa12dMbHJrHVFRt8JyO,https://p.scdn.co/mp3-preview/fa6fa6f6f363be29...,228185.0,True,Bacc At It Again,0.948,...,-5.725,0.0,0.1680,0.00124,0.000001,0.0716,0.856,135.979,4.0,61.0
2124,Bad Bad BadYoung Thug Featuring Lil Baby,Young Thug Featuring Lil Baby,Bad Bad Bad,"['atl hip hop', 'atl trap', 'gangster rap', 'm...",1GeNui6m825V8jP4uKiIaH,https://p.scdn.co/mp3-preview/909f15e56869916e...,149040.0,True,So Much Fun,0.974,...,-8.888,1.0,0.1840,0.09760,0.000000,0.1510,0.892,111.959,4.0,82.0
2125,Bad Bad BadYoung Thug Featuring Lil Baby,Young Thug Featuring Lil Baby,Bad Bad Bad,"['atl hip hop', 'atl trap', 'gangster rap', 'm...",1GeNui6m825V8jP4uKiIaH,https://p.scdn.co/mp3-preview/909f15e56869916e...,149040.0,True,So Much Fun,0.974,...,-8.888,1.0,0.1840,0.09760,0.000000,0.1510,0.892,111.959,4.0,82.0
2156,Bad GuyBillie Eilish,Billie Eilish,Bad Guy,"['electropop', 'pop']",2Fxmhks0bxGSBdJ92vM42m,NaN,194087.0,False,WHEN WE ALL FALL ASLEE,0.701,...,-10.965,1.0,0.3750,0.32800,0.130000,0.1000,0.562,135.128,4.0,95.0
2157,Bad GuyBillie Eilish,Billie Eilish,Bad Guy,"['electropop', 'pop']",2Fxmhks0bxGSBdJ92vM42m,NaN,194087.0,False,WHEN WE ALL FALL ASLEE,0.701,...,-10.965,1.0,0.3750,0.32800,0.130000,0.1000,0.562,135.128,4.0,96.0
2197,Baila Baila BailaOzuna x Daddy Yankee x J Balv...,Ozuna x Daddy Yankee x J Balvin x Farruko x An...,Baila Baila Baila,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2198,Baila Baila BailaOzuna x Daddy Yankee x J Balv...,Ozuna x Daddy Yankee x J Balvin x Farruko x An...,Baila Baila Baila,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
billboard_song = billboard.groupby("song_id").agg(

    final_weeks_on_chart=("weeks_on_chart", "max"),

    best_peak_position=("peak_position", "min")

).reset_index()

In [21]:
print("Billboard song-level shape:", billboard_song.shape)

billboard_song.head()

Billboard song-level shape: (29389, 3)

,song_id,final_weeks_on_chart,best_peak_position
0,"""B"" GirlsYoung And Restless",15,54
1,"""Cherry Cherry"" from Hot August NightNeil Diamond",10,31
2,"""Having A Party"" MedleyThe Ovations (Featuring...",9,56
3,"""Joy"" Pt. IIsaac Hayes",9,30
4,"""Roots"" MedleyQuincy Jones",7,57

In [22]:
data = billboard_song.merge(

    audio_ft,

    on="song_id",

    how="inner"

)

In [23]:
print("Merged shape:", data.shape)

print("Unique songs:", data["song_id"].nunique())

Merged shape: (29500, 24)
Unique songs: 29383

In [24]:
duplicates = data[data["song_id"].duplicated(keep=False)].sort_values("song_id")

duplicates[["song_id", "song", "performer"]].head(30)

,song_id,song,performer
340,24/7Meek Mill Featuring Ella Mai,24/7,Meek Mill Featuring Ella Mai
341,24/7Meek Mill Featuring Ella Mai,24/7,Meek Mill Featuring Ella Mai
537,A Holly Jolly ChristmasBurl Ives,A Holly Jolly Christmas,Burl Ives
538,A Holly Jolly ChristmasBurl Ives,A Holly Jolly Christmas,Burl Ives
807,Act UpCity Girls,Act Up,City Girls
808,Act UpCity Girls,Act Up,City Girls
1112,All I Want For Christmas Is YouMariah Carey,All I Want For Christmas Is You,Mariah Carey
1113,All I Want For Christmas Is YouMariah Carey,All I Want For Christmas Is You,Mariah Carey
1200,All The Good Girls Go To HellBillie Eilish,All The Good Girls Go To Hell,Billie Eilish
1201,All The Good Girls Go To HellBillie Eilish,All The Good Girls Go To Hell,Billie Eilish
1237,All To MyselfDan + Shay,All To Myself,Dan + Shay
1238,All To MyselfDan + Shay,All To Myself,Dan + Shay
2043,"Bacc At It AgainYella Beezy, Gucci Mane & Quavo",Bacc At It Again,"Yella Beezy, Gucci Mane & Quavo"
2042,"Bacc At It AgainYella Beezy, Gucci Mane & Quavo",Bacc At It Again,"Yella Beezy, Gucci Mane & Quavo"
2127,Bad Bad BadYoung Thug Featuring Lil Baby,Bad Bad Bad,Young Thug Featuring Lil Baby
2128,Bad Bad BadYoung Thug Featuring Lil Baby,Bad Bad Bad,Young Thug Featuring Lil Baby
2159,Bad GuyBillie Eilish,Bad Guy,Billie Eilish
2160,Bad GuyBillie Eilish,Bad Guy,Billie Eilish
2199,Baila Baila BailaOzuna x Daddy Yankee x J Balv...,Baila Baila Baila,Ozuna x Daddy Yankee x J Balvin x Farruko x An...
2200,Baila Baila BailaOzuna x Daddy Yankee x J Balv...,Baila Baila Baila,Ozuna x Daddy Yankee x J Balvin x Farruko x An...
2482,Beer Never Broke My HeartLuke Combs,Beer Never Broke My Heart,Luke Combs
2483,Beer Never Broke My HeartLuke Combs,Beer Never Broke My Heart,Luke Combs
2491,Before I Let GoBeyonce,Before I Let Go,Beyonce
2492,Before I Let GoBeyonce,Before I Let Go,Beyonce
2632,BetterKhalid,Better,Khalid
2633,BetterKhalid,Better,Khalid
2700,Big Ole FreakMegan Thee Stallion,Big Ole Freak,Megan Thee Stallion
2701,Big Ole FreakMegan Thee Stallion,Big Ole Freak,Megan Thee Stallion
3606,Call You MineThe Chainsmokers & Bebe Rexha,Call You Mine,The Chainsmokers & Bebe Rexha
3605,Call You MineThe Chainsmokers & Bebe Rexha,Call You Mine,The Chainsmokers & Bebe Rexha

In [26]:
print("Number of duplicated song IDs:", duplicates["song_id"].nunique())
duplicates.groupby("song_id").size().value_counts()

Number of duplicated song IDs: 117

2    117
Name: count, dtype: int64

In [27]:
duplicates.head(10).T

,340,341,537,538,807,808,1112,1113,1200,1201
song_id,24/7Meek Mill Featuring Ella Mai,24/7Meek Mill Featuring Ella Mai,A Holly Jolly ChristmasBurl Ives,A Holly Jolly ChristmasBurl Ives,Act UpCity Girls,Act UpCity Girls,All I Want For Christmas Is YouMariah Carey,All I Want For Christmas Is YouMariah Carey,All The Good Girls Go To HellBillie Eilish,All The Good Girls Go To HellBillie Eilish
final_weeks_on_chart,19,19,19,19,21,21,43,43,7,7
best_peak_position,54,54,4,4,26,26,1,1,46,46
performer,Meek Mill Featuring Ella Mai,Meek Mill Featuring Ella Mai,Burl Ives,Burl Ives,City Girls,City Girls,Mariah Carey,Mariah Carey,Billie Eilish,Billie Eilish
song,24/7,24/7,A Holly Jolly Christmas,A Holly Jolly Christmas,Act Up,Act Up,All I Want For Christmas Is You,All I Want For Christmas Is You,All The Good Girls Go To Hell,All The Good Girls Go To Hell
spotify_genre,"['hip hop', 'philly rap', 'pop rap', 'rap', 's...","['hip hop', 'philly rap', 'pop rap', 'rap', 's...","['adult standards', 'american folk revival']","['adult standards', 'american folk revival']","['pop', 'pop rap', 'trap queen']","['pop', 'pop rap', 'trap queen']","['dance pop', 'pop', 'r&b', 'urban contemporary']","['dance pop', 'pop', 'r&b', 'urban contemporary']","['electropop', 'pop']","['electropop', 'pop']"
spotify_track_id,NaN,NaN,65Q2mv3UlVi9eO70OpsmSe,65Q2mv3UlVi9eO70OpsmSe,3A2yGHWIzmGEIolwonU69h,3A2yGHWIzmGEIolwonU69h,0bYg9bo50gSsH3LtXe2SQn,0bYg9bo50gSsH3LtXe2SQn,6IRdLKIyS4p7XNiP8r6rsx,6IRdLKIyS4p7XNiP8r6rsx
spotify_track_preview_url,NaN,NaN,NaN,NaN,NaN,NaN,https://p.scdn.co/mp3-preview/ab4f06069148ef85...,https://p.scdn.co/mp3-preview/ab4f06069148ef85...,NaN,NaN
spotify_track_duration_ms,NaN,NaN,135533.0,135533.0,158332.0,158332.0,241106.0,241106.0,168839.0,168839.0
spotify_track_explicit,NaN,NaN,False,False,True,True,False,False,False,False
spotify_track_album,NaN,NaN,Have A Holly Jolly Christmas,Have A Holly Jolly Christmas,Girl Code,Girl Code,Merry Christmas,Merry Christmas,WHEN WE ALL FALL ASLEE,WHEN WE ALL FALL ASLEE
danceability,NaN,NaN,0.683,0.674,0.938,0.938,0.335,0.335,0.726,0.726
energy,NaN,NaN,0.375,0.37,0.638,0.638,0.625,0.625,0.444,0.444
key,NaN,NaN,0.0,0.0,8.0,8.0,7.0,7.0,8.0,8.0
loudness,NaN,NaN,-13.056,-12.937,-4.713,-4.713,-7.462,-7.462,-8.922,-8.922
mode,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
speechiness,NaN,NaN,0.0303,0.0309,0.189,0.189,0.0386,0.0386,0.372,0.372
acousticness,NaN,NaN,0.579,0.616,0.0167,0.0167,0.164,0.164,0.283,0.283
instrumentalness,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.143,0.143
liveness,NaN,NaN,0.076,0.0781,0.111,0.111,0.0708,0.0708,0.177,0.177
valence,NaN,NaN,0.888,0.862,0.313,0.313,0.346,0.346,0.569,0.569
tempo,NaN,NaN,140.467,140.352,97.075,97.075,150.277,150.277,185.044,185.044
time_signature,NaN,NaN,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
spotify_track_popularity,NaN,NaN,80.0,82.0,79.0,80.0,95.0,97.0,86.0,87.0